# This is a basic workflow to help you get started with Actions

name: Flask CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Creates a python3 virtual environment
      - name: Create python3 venv
        run: python3 -m venv venv
      
      # Activates the python3 virtual environment
      - name: Activate venv
        run: source $GITHUB_WORKSPACE/venv/bin/activate
      
      # Installing all the pip packages using requirements.txt file
      - name: Installing pip requirements
        run: pip3 install -r requirements.txt
      
      # Installing pre-commit for the repository
      - name: Installing pre-commit for the repository
        run: pre-commit install
      
      # Running pre-commit hooks on all the files of repository
      - name: Run pre-commit on all files
        run: pre-commit run --all-files
        
